// <auto-generated />
using System;
using AngularTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AngularTask.Migrations
{
    [DbContext(typeof(ContentDbContext))]
    [Migration("20230305172457_AddContentItemupdateSeedData")]
    partial class AddContentItemupdateSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("AngularTask.Models.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is a sample content.",
                            DownloadUrl = "https://example.com/sample-content-1.pdf",
                            Title = "Sample Content 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is another sample content.",
                            DownloadUrl = "https://example.com/sample-content-2.pdf",
                            Title = "Sample Content 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is yet another sample content.",
                            DownloadUrl = "https://example.com/sample-content-3.pdf",
                            Title = "Sample Content 3"
                        });
                });

            modelBuilder.Entity("AngularTask.Models.ContentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalsDownloadsA4")
                        .HasColumnType("int");

                    b.Property<int>("TotalsDownloadsimage")
                        .HasColumnType("int");

                    b.Property<int>("TotalsDownloadsmobile")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContentItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 3, 5, 21, 24, 56, 333, DateTimeKind.Local).AddTicks(8412),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse quis risus quam. Nulla quis mauris vel libero mollis facilisis. Ut vitae fringilla nisi. Nam eu augue eget arcu rutrum vestibulum. In hac habitasse platea dictumst. Curabitur id urna at mauris auctor malesuada. Sed non ipsum ac nisi iaculis ullamcorper vel vel lectus.",
                            DownloadCount = 0,
                            ImageUrl = "https://example.com/image1.jpg",
                            ThumbnailUrl = "https://example.com/thumb1.jpg",
                            Title = "First Item",
                            TotalsDownloadsA4 = 0,
                            TotalsDownloadsimage = 0,
                            TotalsDownloadsmobile = 0,
                            UpdatedAt = new DateTime(2023, 3, 5, 21, 24, 56, 335, DateTimeKind.Local).AddTicks(5159)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2023, 3, 5, 21, 24, 56, 335, DateTimeKind.Local).AddTicks(5780),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse quis risus quam. Nulla quis mauris vel libero mollis facilisis. Ut vitae fringilla nisi. Nam eu augue eget arcu rutrum vestibulum. In hac habitasse platea dictumst. Curabitur id urna at mauris auctor malesuada. Sed non ipsum ac nisi iaculis ullamcorper vel vel lectus.",
                            DownloadCount = 0,
                            ImageUrl = "https://example.com/image2.jpg",
                            ThumbnailUrl = "https://example.com/thumb2.jpg",
                            Title = "Second Item",
                            TotalsDownloadsA4 = 0,
                            TotalsDownloadsimage = 0,
                            TotalsDownloadsmobile = 0,
                            UpdatedAt = new DateTime(2023, 3, 5, 21, 24, 56, 335, DateTimeKind.Local).AddTicks(5786)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2023, 3, 5, 21, 24, 56, 335, DateTimeKind.Local).AddTicks(5789),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse quis risus quam. Nulla quis mauris vel libero mollis facilisis. Ut vitae fringilla nisi. Nam eu augue eget arcu rutrum vestibulum. In hac habitasse platea dictumst. Curabitur id urna at mauris auctor malesuada. Sed non ipsum ac nisi iaculis ullamcorper vel vel lectus",
                            DownloadCount = 0,
                            ImageUrl = "https://example.com/image3.jpg",
                            ThumbnailUrl = "https://example.com/thumb3.jpg",
                            Title = "Third Item",
                            TotalsDownloadsA4 = 0,
                            TotalsDownloadsimage = 0,
                            TotalsDownloadsmobile = 0,
                            UpdatedAt = new DateTime(2023, 3, 5, 21, 24, 56, 335, DateTimeKind.Local).AddTicks(5791)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2023, 3, 5, 21, 24, 56, 335, DateTimeKind.Local).AddTicks(5793),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse quis risus quam. Nulla quis mauris vel libero mollis facilisis. Ut vitae fringilla nisi. Nam eu augue eget arcu rutrum vestibulum. In hac habitasse platea dictumst. Curabitur id urna at mauris auctor malesuada. Sed non ipsum ac nisi iaculis ullamcorper vel vel lectus.",
                            DownloadCount = 0,
                            ImageUrl = "https://example.com/image1.jpg",
                            ThumbnailUrl = "https://example.com/thumb1.jpg",
                            Title = "Fourth Item",
                            TotalsDownloadsA4 = 0,
                            TotalsDownloadsimage = 0,
                            TotalsDownloadsmobile = 0,
                            UpdatedAt = new DateTime(2023, 3, 5, 21, 24, 56, 335, DateTimeKind.Local).AddTicks(5795)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2023, 3, 5, 21, 24, 56, 335, DateTimeKind.Local).AddTicks(5799),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse quis risus quam. Nulla quis mauris vel libero mollis facilisis. Ut vitae fringilla nisi. Nam eu augue eget arcu rutrum vestibulum. In hac habitasse platea dictumst. Curabitur id urna at mauris auctor malesuada. Sed non ipsum ac nisi iaculis ullamcorper vel vel lectus.",
                            DownloadCount = 0,
                            ImageUrl = "https://example.com/image2.jpg",
                            ThumbnailUrl = "https://example.com/thumb2.jpg",
                            Title = "Fifth Item",
                            TotalsDownloadsA4 = 0,
                            TotalsDownloadsimage = 0,
                            TotalsDownloadsmobile = 0,
                            UpdatedAt = new DateTime(2023, 3, 5, 21, 24, 56, 335, DateTimeKind.Local).AddTicks(5800)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2023, 3, 5, 21, 24, 56, 335, DateTimeKind.Local).AddTicks(5813),
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse quis risus quam. Nulla quis mauris vel libero mollis facilisis. Ut vitae fringilla nisi. Nam eu augue eget arcu rutrum vestibulum. In hac habitasse platea dictumst. Curabitur id urna at mauris auctor malesuada. Sed non ipsum ac nisi iaculis ullamcorper vel vel lectus.",
                            DownloadCount = 0,
                            ImageUrl = "https://example.com/image3.jpg",
                            ThumbnailUrl = "https://example.com/thumb3.jpg",
                            Title = "Sixth Item",
                            TotalsDownloadsA4 = 0,
                            TotalsDownloadsimage = 0,
                            TotalsDownloadsmobile = 0,
                            UpdatedAt = new DateTime(2023, 3, 5, 21, 24, 56, 335, DateTimeKind.Local).AddTicks(5814)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
